
package org.eapo.service.sopranoDataService.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GengenServiceImplService", targetNamespace = "http://gengenimpl.service.soprano.eapo.org/", wsdlLocation = "http://192.168.3.229:8080/SopranoV522/getgengen?wsdl")
public class GengenServiceImplService
    extends Service
{

    private final static URL GENGENSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException GENGENSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName GENGENSERVICEIMPLSERVICE_QNAME = new QName("http://gengenimpl.service.soprano.eapo.org/", "GengenServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.3.229:8080/SopranoV522/getgengen?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GENGENSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        GENGENSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public GengenServiceImplService() {
        super(__getWsdlLocation(), GENGENSERVICEIMPLSERVICE_QNAME);
    }

    public GengenServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GENGENSERVICEIMPLSERVICE_QNAME, features);
    }

    public GengenServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, GENGENSERVICEIMPLSERVICE_QNAME);
    }

    public GengenServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GENGENSERVICEIMPLSERVICE_QNAME, features);
    }

    public GengenServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GengenServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GengenService
     */
    @WebEndpoint(name = "GengenServiceImplPort")
    public GengenService getGengenServiceImplPort() {
        return super.getPort(new QName("http://gengenimpl.service.soprano.eapo.org/", "GengenServiceImplPort"), GengenService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GengenService
     */
    @WebEndpoint(name = "GengenServiceImplPort")
    public GengenService getGengenServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://gengenimpl.service.soprano.eapo.org/", "GengenServiceImplPort"), GengenService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GENGENSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw GENGENSERVICEIMPLSERVICE_EXCEPTION;
        }
        return GENGENSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
